/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/chart/BarChart.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ConsoleChart: typeof import('./src/components/chart/ConsoleChart.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeatMap: typeof import('./src/components/chart/HeatMap.vue')['default']
    HomeTab: typeof import('./src/components/HomeTab.vue')['default']
    IndicatorCard: typeof import('./src/components/IndicatorCard.vue')['default']
    LineChart: typeof import('./src/components/chart/LineChart.vue')['default']
    NavBar: typeof import('./src/components/bar/NavBar.vue')['default']
    PieChart: typeof import('./src/components/chart/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChart: typeof import('./src/components/chart/ScatterChart.vue')['default']
    StackBarChart: typeof import('./src/components/chart/StackBarChart.vue')['default']
    SwiperComponent: typeof import('./src/components/SwiperComponent.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
    WordCloudChart: typeof import('./src/components/chart/WordCloudChart.vue')['default']
  }
}
